### ISSUE TITLE
Failed to open gpio direction for writing!

### ISSUE THREAD

**Issue by filip-dahlberg** [Infineon/cli-optiga-trust-x#2]
CLI commands that are are communicating with Optiga Trust M all outputs the warnings:
Failed to open gpio direction for writing!
Failed to open gpio direction for writing!
Failed to write value! Erro code = 9, fd = -1
Failed to write value! Erro code = 9, fd = -1
Failed to write value! Erro code = 9, fd = -1
Failed to write value! Erro code = 9, fd = -1

I would appreciate any help to resolve this. 

Kind regards from Sweden

**Comment by rampageservices** [comment]
What is your target system?
You may need to create a custom PAL config for your custom system if it is not a Raspberry Pi.
