### ISSUE TITLE
DOS line endings make difficult to submit patches from Linux

### ISSUE THREAD

**Issue by rampageservices** [Infineon/cli-optiga-trust-x#3]
Hello,

I have some PRs that I would like to submit but the line endings in the Makefile are DOS carriage returns. 
I can set fileformat=unix in vim and create the commits with the changes but it modifies the entire file. It's probably not good practice to create a PR of an entire file just for a few line changes. 
Can you convert the line endings for all the files to unix as this package is intended to run on Linux based systems? It will make it easier to submit targeted PRs.
Thanks!

**Comment by ayushev** [comment]
Hello @rampageservices 

all PR are warmly welcome. Regarding your request, could you please check this out https://github.com/Infineon/cli-optiga-trust-x/commit/a6978146e8a0ac135720bf5e32ef8d3678437feb ?

**Comment by rampageservices** [comment]
Looks good. I'll rebase on top of this commit and submit our PRs. For such a large refactor especially for code used in a security setting it was better that you did this as the original author instead of someone else submitting a PR.
Thanks for the quick reply!
